version: '3'
services:
  web-app:
    build: .
    command: bash -c "npm install sqlite3 && npm run compile && npm start"
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app 